### PR TITLE
Update Pipfile.lock for data workflow

### PR DESCRIPTION
**Pull request by ktheory**
Hi! I'm trying to get stats working for F3 Churham.

The data workflow has failed recently, possibly b/c of incompatible `numpy` and `pandas` versions.

This is an attempt to fix it by upgrading the `numpy` version. I generated the Pipfile.lock by running `pipenv install` on a clean checkout.

Example of a data workflow failure log:
https://github.com/f3peakcity/f3_bot/actions/runs/9957065524/job/27508277007

### CODE REVIEW

**Comment by ktheory** [comment]
@mikeyrcamp -- Btw, I'm friends with @jcampbell 😄 

Here's the Churham looker dashboard show missing stats since ~May 14:
https://lookerstudio.google.com/u/0/reporting/2d3f2228-6c60-400c-97e8-3e8fc945f3fe/page/WICTD

**Review by mikeyrcamp — APPROVED** [review]

**Comment by mikeyrcamp** [comment]
Didn't resolve the issue.

**Comment by mikeyrcamp** [comment]
https://github.com/f3peakcity/f3_bot/actions/runs/10044043824

**Comment by ktheory** [comment]
Rats. I'll put in a bit of effort to try to reproduce the error locally on my Mac.

Other ideas to try include upgrading `pandas` and/or upgrading python from 3.9. 🤷  FWIW, I have not done much python development, so I'm figuring it out as a go.

**Pull request merged**
